-- 코드를 입력하세요
SELECT A.CAR_ID, A.CAR_TYPE
    , FLOOR(30 * A.DAILY_FEE * (1 - IFNULL(C.DISCOUNT_RATE,0) / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
ON  C.CAR_TYPE = A.CAR_TYPE
    AND C.DURATION_TYPE = '30일 이상'
WHERE A.CAR_TYPE IN ('세단', 'SUV')
    AND A.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30'
            AND END_DATE >= '2022-11-01'
    )
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC