SELECT 
    c.CAR_ID,
    c.CAR_TYPE,
    FLOOR(c.DAILY_FEE * 30 * (1 - IFNULL(d.DISCOUNT_RATE, 0) / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
-- 30일 이상 할인율 JOIN
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d
    ON c.CAR_TYPE = d.CAR_TYPE
    AND d.DURATION_TYPE = '30일 이상'
-- 11월 1일~30일 기간에 겹치는 대여 기록 제외
WHERE c.CAR_TYPE IN ('세단', 'SUV')
  AND c.CAR_ID NOT IN (
      SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE START_DATE <= '2022-11-30'
        AND END_DATE >= '2022-11-01'
  )
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;