-- 코드를 입력하세요
SELECT A.NAME, A.DATETIME
FROM (
    SELECT C.NAME, C.DATETIME, RANK() OVER (ORDER BY C.DATETIME) RNK
    FROM ANIMAL_INS C
    LEFT JOIN ANIMAL_OUTS B
    ON C.ANIMAL_ID = B.ANIMAL_ID
    WHERE B.ANIMAL_ID IS NULL
) A
WHERE A.RNK <= 3
ORDER BY A.DATETIME
    