SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE A
JOIN (
    SELECT MEMBER_ID, RANK() OVER (ORDER BY COUNT(1) DESC) AS RNK
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
) C ON A.MEMBER_ID = C.MEMBER_ID AND C.RNK = 1
JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
ORDER BY B.REVIEW_DATE, B.REVIEW_TEXT