SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO A
JOIN FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
JOIN (
    SELECT ID, RANK() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) RNK
    FROM FISH_INFO
) C
ON A.ID = C.ID AND C.RNK = 1
ORDER BY A.ID