-- 코드를 입력하세요
SELECT A.CATEGORY, A.PRICE, A.PRODUCT_NAME
FROM (
    SELECT CATEGORY, PRICE, PRODUCT_NAME, 
        RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) RNK
    FROM FOOD_PRODUCT
) A
WHERE A.RNK = 1 AND A.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY A.PRICE DESC;


SELECT A.CATEGORY, A.PRICE, A.PRODUCT_NAME
FROM (
    SELECT CATEGORY, PRICE, PRODUCT_NAME, 
        RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) RNK
    FROM FOOD_PRODUCT
) A
WHERE A.RNK = 1
    AND A.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY A.PRICE DESC